Use safe_malloc instead of new when creating new_envoy_map_entry
envoyproxy/envoy-mobile pull request #2632
Opened 2022-10-24 18:44 UTC by RyanTheOptimist

Use safe_malloc instead of new when creating new_envoy_map_entry
since release_envoy_map uses free instead of delete. Found when 
building this code internally with some sort of strict checking enabled
    
Signed-off-by: Ryan Hamilton <rch@google.com>

Risk Level: Low
Testing: Existing tests
Docs Changes: N/A
Release Notes: N/A

2022-10-24 18:48 UTC, RyanTheOptimist commented
/assign @snowp

2022-10-24 18:48 UTC, RyanTheOptimist commented
@snowp I sent this your way based on the Obj-C/C/C++ discussion we had on Slack. Feel free to redirect though!

2022-10-24 19:34 UTC, snowp requested changes
Nice this makes sense to me, one suggestion

Is this check something we can enable for the EM build? Or is this some internal secret sauce?

2022-10-25 17:39 UTC, RyanTheOptimist commented
> Nice this makes sense to me, one suggestion
> 
> Is this check something we can enable for the EM build? Or is this some internal secret sauce?

Interesting question. It does look like an internal secret sauce thing in tcmalloc, according to some internal docs. However, the chromium version of tcmalloco has something basically similar. There error comes from here:

https://chromium.googlesource.com/chromium/src/third_party/tcmalloc/chromium/+/refs/heads/main/src/debugallocation.cc#474

So it might be something to investigate, but i don't think it works out of the box.

2022-10-25 17:39 UTC, RyanTheOptimist commented on test/common/http/header_utility_test.cc
> +      static_cast<envoy_map_entry*>(safe_malloc(sizeof(envoy_map_entry) * 0));
Good question! I was able to do this for both this test and the subsequent one. The rest of the tests, though, seem more elaborate. They set up envoy_map instances in which the envoy_data is wired up to use `envoy_test_release()` when releasing the data to do tracking. `makeEnvoyMap` seems to use `copyToBridgeData()` to populate the map which I think makes this a non-starter. But I'm not entirely familiar with this code so maybe there's a cleaner approach?

2022-10-26 17:26 UTC, snowp approved these changes
Thanks!

2022-10-26 17:31 UTC, jpsim commented
/retest

2022-10-31 18:37 UTC, merged